/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TimelineEntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "timelineEntry";
};

export type StackTagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "stackTag";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  employer?: TimelineEntryReference;
  client?: string;
  role?: string;
  year?: number;
  endYear?: number;
  engagement?: "freelance" | "full-time" | "student";
  state?: "active" | "maintained" | "archived" | "cancelled";
  stack?: Array<
    {
      _key: string;
    } & StackTagReference
  >;
  featured?: boolean;
  tooling?: {
    en?: string;
    nl?: string;
  };
  featureTooling?: boolean;
  summary?: {
    en?: string;
    nl?: string;
  };
  deck?: {
    en?: string;
    nl?: string;
  };
  description?: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  screenshots?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  outcome?: {
    en?: string;
    nl?: string;
  };
  body?: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  gallery?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    frame?: "phone" | "tablet" | "browser" | "none";
    caption?: {
      en?: string;
      nl?: string;
    };
    _type: "shot";
    _key: string;
  }>;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  liveUrl?: string;
  githubUrl?: string;
  writeupUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type StackTag = {
  _id: string;
  _type: "stackTag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: "mobile" | "web" | "frontend" | "tooling" | "other";
};

export type TimelineEntry = {
  _id: string;
  _type: "timelineEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organisation?: string;
  title?: string;
  group?: "freelance" | "employed" | "education";
  startDate?: string;
  endDate?: string;
  description?: {
    en?: string;
    nl?: string;
  };
  location?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  socials?: Array<{
    platform?: "github" | "linkedin" | "bluesky" | "instagram" | "mastodon";
    url?: string;
    label?: string;
    _key: string;
  }>;
  metaDescription?: {
    en?: string;
    nl?: string;
  };
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Availability = {
  _id: string;
  _type: "availability";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: "available" | "after-hours" | "unavailable";
  message?: {
    en?: string;
    nl?: string;
  };
  nextOpening?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: {
    en?: string;
    nl?: string;
  };
  roleLine?: {
    en?: string;
    nl?: string;
  };
  filterIntro?: {
    en?: string;
    nl?: string;
  };
  aboutHeadline?: {
    en?: string;
    nl?: string;
  };
  bio?: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  beyondCode?: Array<{
    title?: {
      en?: string;
      nl?: string;
    };
    body?: {
      en?: string;
      nl?: string;
    };
    _key: string;
  }>;
  cvEn?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  cvNl?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  location?: string;
  email?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  vatNumber?: string;
  copyrightYear?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TimelineEntryReference
  | StackTagReference
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | StackTag
  | TimelineEntry
  | SiteSettings
  | Availability
  | SanityFileAssetReference
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/about.ts
// Variable: ABOUT_QUERY
// Query: {    "profile": *[_id == "profile"][0]{      name,      tagline,      aboutHeadline,      bio,      beyondCode[]{ title, body },      location,      email,      socialLinks,      "cvEnUrl": cvEn.asset->url,      "cvNlUrl": cvNl.asset->url,      vatNumber,      copyrightYear,      "portraitUrl": portrait.asset->url    },    "timeline": *[_type == "timelineEntry"] | order(startDate desc) {      _id,      organisation,      title,      group,      startDate,      endDate,      description,      location    },    "ownApps": *[_type == "project" && engagement == "owner"] | order(featured desc, year desc) {      _id,      name,      "slug": slug.current,      deck,      year,      state,      liveUrl    }  }
export type ABOUT_QUERY_RESULT = {
  profile:
    | {
        name: null;
        tagline: null;
        aboutHeadline: null;
        bio: null;
        beyondCode: null;
        location: null;
        email: null;
        socialLinks: null;
        cvEnUrl: null;
        cvNlUrl: null;
        vatNumber: null;
        copyrightYear: null;
        portraitUrl: null;
      }
    | {
        name: string | null;
        tagline: null;
        aboutHeadline: null;
        bio: null;
        beyondCode: null;
        location: null;
        email: null;
        socialLinks: null;
        cvEnUrl: null;
        cvNlUrl: null;
        vatNumber: null;
        copyrightYear: null;
        portraitUrl: null;
      }
    | {
        name: null;
        tagline: null;
        aboutHeadline: null;
        bio: null;
        beyondCode: null;
        location: string | null;
        email: null;
        socialLinks: null;
        cvEnUrl: null;
        cvNlUrl: null;
        vatNumber: null;
        copyrightYear: null;
        portraitUrl: null;
      }
    | {
        name: null;
        tagline: null;
        aboutHeadline: null;
        bio: null;
        beyondCode: null;
        location: null;
        email: string | null;
        socialLinks: null;
        cvEnUrl: null;
        cvNlUrl: null;
        vatNumber: null;
        copyrightYear: null;
        portraitUrl: null;
      }
    | {
        name: string | null;
        tagline: {
          en?: string;
          nl?: string;
        } | null;
        aboutHeadline: {
          en?: string;
          nl?: string;
        } | null;
        bio: {
          en?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
          nl?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
        } | null;
        beyondCode: Array<{
          title: {
            en?: string;
            nl?: string;
          } | null;
          body: {
            en?: string;
            nl?: string;
          } | null;
        }> | null;
        location: string | null;
        email: string | null;
        socialLinks: Array<{
          label?: string;
          url?: string;
          _key: string;
        }> | null;
        cvEnUrl: string | null;
        cvNlUrl: string | null;
        vatNumber: string | null;
        copyrightYear: number | null;
        portraitUrl: string | null;
      }
    | null;
  timeline: Array<{
    _id: string;
    organisation: string | null;
    title: string | null;
    group: "education" | "employed" | "freelance" | null;
    startDate: string | null;
    endDate: string | null;
    description: {
      en?: string;
      nl?: string;
    } | null;
    location: string | null;
  }>;
  ownApps: Array<never>;
};

// Source: src/sanity/queries/availability.ts
// Variable: AVAILABILITY_QUERY
// Query: *[_id == "availability"][0]{    status,    message,    nextOpening  }
export type AVAILABILITY_QUERY_RESULT =
  | {
      status: null;
      message: null;
      nextOpening: null;
    }
  | {
      status: "after-hours" | "available" | "unavailable" | null;
      message: {
        en?: string;
        nl?: string;
      } | null;
      nextOpening: string | null;
    }
  | null;

// Source: src/sanity/queries/case-study.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    year,    endYear,    state,    engagement,    role,    client,    deck,    summary,    description,    outcome,    body,    liveUrl,    githubUrl,    writeupUrl,    featured,    "employer": employer->{      _id,      name,      "slug": "employer-" + lower(name)    },    "stack": stack[]->{      _id,      name,      "slug": slug.current,      category    },    "coverUrl": cover.asset->url,    "coverAlt": cover.alt,    "screenshots": screenshots[]{      _key,      alt,      "asset": asset->    },    "gallery": gallery[]{      _key,      frame,      caption,      "imageUrl": image.asset->url,      "width": image.asset->metadata.dimensions.width,      "height": image.asset->metadata.dimensions.height    },    "related": *[      _type == "project"      && slug.current != $slug      && references(^.employer._ref)    ] | order(featured desc, year desc) [0...3] {      _id,      name,      "slug": slug.current,      year,      deck    }  }
export type CASE_STUDY_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  year: number | null;
  endYear: number | null;
  state: "active" | "archived" | "cancelled" | "maintained" | null;
  engagement: "freelance" | "full-time" | "student" | null;
  role: string | null;
  client: string | null;
  deck: {
    en?: string;
    nl?: string;
  } | null;
  summary: {
    en?: string;
    nl?: string;
  } | null;
  description: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | null;
  outcome: {
    en?: string;
    nl?: string;
  } | null;
  body: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | null;
  liveUrl: string | null;
  githubUrl: string | null;
  writeupUrl: string | null;
  featured: boolean | null;
  employer: {
    _id: string;
    name: null;
    slug: null;
  } | null;
  stack: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    category: "frontend" | "mobile" | "other" | "tooling" | "web" | null;
  }> | null;
  coverUrl: string | null;
  coverAlt: string | null;
  screenshots: Array<{
    _key: string;
    alt: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  }> | null;
  gallery: Array<{
    _key: string;
    frame: "browser" | "none" | "phone" | "tablet" | null;
    caption: {
      en?: string;
      nl?: string;
    } | null;
    imageUrl: string | null;
    width: number | null;
    height: number | null;
  }> | null;
  related: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    year: number | null;
    deck: {
      en?: string;
      nl?: string;
    } | null;
  }>;
} | null;

// Source: src/sanity/queries/case-study.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current  }
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries/profile.ts
// Variable: PROFILE_QUERY
// Query: *[_id == "profile"][0]{    name,    tagline,    roleLine,    filterIntro,    aboutHeadline,    bio,    "portraitUrl": portrait.asset->url,    beyondCode[]{      title,      body    },    location,    email,    socialLinks,    "cvEnUrl": cvEn.asset->url,    "cvNlUrl": cvNl.asset->url,    vatNumber,    copyrightYear  }
export type PROFILE_QUERY_RESULT =
  | {
      name: null;
      tagline: null;
      roleLine: null;
      filterIntro: null;
      aboutHeadline: null;
      bio: null;
      portraitUrl: null;
      beyondCode: null;
      location: null;
      email: null;
      socialLinks: null;
      cvEnUrl: null;
      cvNlUrl: null;
      vatNumber: null;
      copyrightYear: null;
    }
  | {
      name: string | null;
      tagline: null;
      roleLine: null;
      filterIntro: null;
      aboutHeadline: null;
      bio: null;
      portraitUrl: null;
      beyondCode: null;
      location: null;
      email: null;
      socialLinks: null;
      cvEnUrl: null;
      cvNlUrl: null;
      vatNumber: null;
      copyrightYear: null;
    }
  | {
      name: null;
      tagline: null;
      roleLine: null;
      filterIntro: null;
      aboutHeadline: null;
      bio: null;
      portraitUrl: null;
      beyondCode: null;
      location: string | null;
      email: null;
      socialLinks: null;
      cvEnUrl: null;
      cvNlUrl: null;
      vatNumber: null;
      copyrightYear: null;
    }
  | {
      name: null;
      tagline: null;
      roleLine: null;
      filterIntro: null;
      aboutHeadline: null;
      bio: null;
      portraitUrl: null;
      beyondCode: null;
      location: null;
      email: string | null;
      socialLinks: null;
      cvEnUrl: null;
      cvNlUrl: null;
      vatNumber: null;
      copyrightYear: null;
    }
  | {
      name: string | null;
      tagline: {
        en?: string;
        nl?: string;
      } | null;
      roleLine: {
        en?: string;
        nl?: string;
      } | null;
      filterIntro: {
        en?: string;
        nl?: string;
      } | null;
      aboutHeadline: {
        en?: string;
        nl?: string;
      } | null;
      bio: {
        en?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        nl?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
      } | null;
      portraitUrl: string | null;
      beyondCode: Array<{
        title: {
          en?: string;
          nl?: string;
        } | null;
        body: {
          en?: string;
          nl?: string;
        } | null;
      }> | null;
      location: string | null;
      email: string | null;
      socialLinks: Array<{
        label?: string;
        url?: string;
        _key: string;
      }> | null;
      cvEnUrl: string | null;
      cvNlUrl: string | null;
      vatNumber: string | null;
      copyrightYear: number | null;
    }
  | null;

// Source: src/sanity/queries/projects.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(featured desc, year desc, name asc) {    _id,    name,    "slug": slug.current,    year,    endYear,    state,    engagement,    featured,    role,    client,    deck,    summary,    description,    outcome,    liveUrl,    githubUrl,    writeupUrl,    "employer": employer->{      _id,      name,      "slug": lower(organisation)    },    "stack": stack[]->{      _id,      name,      "slug": slug.current,      category    },    "screenshots": screenshots[]{      _key,      alt,      "asset": asset->    },    tooling,    featureTooling,    "hasBody": count(body.en) > 0,    "galleryCount": count(gallery)  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  year: number | null;
  endYear: number | null;
  state: "active" | "archived" | "cancelled" | "maintained" | null;
  engagement: "freelance" | "full-time" | "student" | null;
  featured: boolean | null;
  role: string | null;
  client: string | null;
  deck: {
    en?: string;
    nl?: string;
  } | null;
  summary: {
    en?: string;
    nl?: string;
  } | null;
  description: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | null;
  outcome: {
    en?: string;
    nl?: string;
  } | null;
  liveUrl: string | null;
  githubUrl: string | null;
  writeupUrl: string | null;
  employer: {
    _id: string;
    name: null;
    slug: string | null;
  } | null;
  stack: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    category: "frontend" | "mobile" | "other" | "tooling" | "web" | null;
  }> | null;
  screenshots: Array<{
    _key: string;
    alt: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  }> | null;
  tooling: {
    en?: string;
    nl?: string;
  } | null;
  featureTooling: boolean | null;
  hasBody: boolean | null;
  galleryCount: number | null;
}>;

// Source: src/sanity/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    email,    socials[]{      platform,      url,      label    },    metaDescription,    "ogImageUrl": ogImage.asset->url  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      email: null;
      socials: null;
      metaDescription: null;
      ogImageUrl: null;
    }
  | {
      email: string | null;
      socials: null;
      metaDescription: null;
      ogImageUrl: null;
    }
  | {
      email: string | null;
      socials: Array<{
        platform:
          | "bluesky"
          | "github"
          | "instagram"
          | "linkedin"
          | "mastodon"
          | null;
        url: string | null;
        label: string | null;
      }> | null;
      metaDescription: {
        en?: string;
        nl?: string;
      } | null;
      ogImageUrl: string | null;
    }
  | null;

// Source: src/sanity/queries/sitemap.ts
// Variable: SITEMAP_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current,    "lastModified": _updatedAt  }
export type SITEMAP_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
  lastModified: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  {\n    "profile": *[_id == "profile"][0]{\n      name,\n      tagline,\n      aboutHeadline,\n      bio,\n      beyondCode[]{ title, body },\n      location,\n      email,\n      socialLinks,\n      "cvEnUrl": cvEn.asset->url,\n      "cvNlUrl": cvNl.asset->url,\n      vatNumber,\n      copyrightYear,\n      "portraitUrl": portrait.asset->url\n    },\n    "timeline": *[_type == "timelineEntry"] | order(startDate desc) {\n      _id,\n      organisation,\n      title,\n      group,\n      startDate,\n      endDate,\n      description,\n      location\n    },\n    "ownApps": *[_type == "project" && engagement == "owner"] | order(featured desc, year desc) {\n      _id,\n      name,\n      "slug": slug.current,\n      deck,\n      year,\n      state,\n      liveUrl\n    }\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_id == "availability"][0]{\n    status,\n    message,\n    nextOpening\n  }\n': AVAILABILITY_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    year,\n    endYear,\n    state,\n    engagement,\n    role,\n    client,\n    deck,\n    summary,\n    description,\n    outcome,\n    body,\n    liveUrl,\n    githubUrl,\n    writeupUrl,\n    featured,\n    "employer": employer->{\n      _id,\n      name,\n      "slug": "employer-" + lower(name)\n    },\n    "stack": stack[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      category\n    },\n    "coverUrl": cover.asset->url,\n    "coverAlt": cover.alt,\n    "screenshots": screenshots[]{\n      _key,\n      alt,\n      "asset": asset->\n    },\n    "gallery": gallery[]{\n      _key,\n      frame,\n      caption,\n      "imageUrl": image.asset->url,\n      "width": image.asset->metadata.dimensions.width,\n      "height": image.asset->metadata.dimensions.height\n    },\n    "related": *[\n      _type == "project"\n      && slug.current != $slug\n      && references(^.employer._ref)\n    ] | order(featured desc, year desc) [0...3] {\n      _id,\n      name,\n      "slug": slug.current,\n      year,\n      deck\n    }\n  }\n': CASE_STUDY_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': CASE_STUDY_SLUGS_QUERY_RESULT;
    '\n  *[_id == "profile"][0]{\n    name,\n    tagline,\n    roleLine,\n    filterIntro,\n    aboutHeadline,\n    bio,\n    "portraitUrl": portrait.asset->url,\n    beyondCode[]{\n      title,\n      body\n    },\n    location,\n    email,\n    socialLinks,\n    "cvEnUrl": cvEn.asset->url,\n    "cvNlUrl": cvNl.asset->url,\n    vatNumber,\n    copyrightYear\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(featured desc, year desc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    year,\n    endYear,\n    state,\n    engagement,\n    featured,\n    role,\n    client,\n    deck,\n    summary,\n    description,\n    outcome,\n    liveUrl,\n    githubUrl,\n    writeupUrl,\n    "employer": employer->{\n      _id,\n      name,\n      "slug": lower(organisation)\n    },\n    "stack": stack[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      category\n    },\n    "screenshots": screenshots[]{\n      _key,\n      alt,\n      "asset": asset->\n    },\n    tooling,\n    featureTooling,\n    "hasBody": count(body.en) > 0,\n    "galleryCount": count(gallery)\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0]{\n    email,\n    socials[]{\n      platform,\n      url,\n      label\n    },\n    metaDescription,\n    "ogImageUrl": ogImage.asset->url\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current,\n    "lastModified": _updatedAt\n  }\n': SITEMAP_SLUGS_QUERY_RESULT;
  }
}
