/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type EmployerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "employer";
};

export type StackTagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "stackTag";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  employer?: EmployerReference;
  client?: string;
  role?: string;
  year?: number;
  endYear?: number;
  engagement?: "freelance" | "full-time" | "owner" | "internship";
  state?: "live" | "done" | "paused" | "cancelled";
  stack?: Array<
    {
      _key: string;
    } & StackTagReference
  >;
  featured?: boolean;
  deck?: {
    en?: string;
    nl?: string;
  };
  description?: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  screenshots?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  outcome?: {
    en?: string;
    nl?: string;
  };
  liveUrl?: string;
  githubUrl?: string;
  writeupUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type StackTag = {
  _id: string;
  _type: "stackTag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: "ios" | "rails" | "frontend" | "tooling" | "other";
};

export type Employer = {
  _id: string;
  _type: "employer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  startYear?: number;
  endYear?: number;
  engagement?: "freelance" | "full-time" | "owner" | "internship";
  description?: {
    en?: string;
    nl?: string;
  };
  order?: number;
};

export type Availability = {
  _id: string;
  _type: "availability";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: "available" | "booked" | "next-opening";
  label?: {
    en?: string;
    nl?: string;
  };
  nextOpening?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: {
    en?: string;
    nl?: string;
  };
  bio?: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  location?: string;
  email?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  cv?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  vatNumber?: string;
  copyrightYear?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | EmployerReference
  | StackTagReference
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | StackTag
  | Employer
  | Availability
  | SanityFileAssetReference
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/about.ts
// Variable: ABOUT_QUERY
// Query: {    "profile": *[_id == "profile"][0]{      name,      tagline,      bio,      location,      email,      socialLinks,      vatNumber,      copyrightYear,      "portrait": portrait{        alt,        "asset": asset->      },      "cv": cv{        "asset": asset->      }    },    "employers": *[_type == "employer"] | order(startYear desc, order desc) {      _id,      name,      role,      startYear,      endYear,      engagement,      "slug": "employer-" + lower(name)    },    "ownApps": *[_type == "project" && engagement == "owner"] | order(featured desc, year desc) {      _id,      name,      "slug": slug.current,      deck,      year,      state,      liveUrl    }  }
export type ABOUT_QUERY_RESULT = {
  profile:
    | {
        name: null;
        tagline: null;
        bio: null;
        location: null;
        email: null;
        socialLinks: null;
        vatNumber: null;
        copyrightYear: null;
        portrait: null;
        cv: null;
      }
    | {
        name: string | null;
        tagline: null;
        bio: null;
        location: null;
        email: null;
        socialLinks: null;
        vatNumber: null;
        copyrightYear: null;
        portrait: null;
        cv: null;
      }
    | {
        name: string | null;
        tagline: {
          en?: string;
          nl?: string;
        } | null;
        bio: {
          en?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
          nl?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
        } | null;
        location: string | null;
        email: string | null;
        socialLinks: Array<{
          label?: string;
          url?: string;
          _key: string;
        }> | null;
        vatNumber: string | null;
        copyrightYear: number | null;
        portrait: {
          alt: null;
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        } | null;
        cv: {
          asset: {
            _id: string;
            _type: "sanity.fileAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            source?: SanityAssetSourceData;
          } | null;
        } | null;
      }
    | null;
  employers: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    startYear: number | null;
    endYear: number | null;
    engagement: "freelance" | "full-time" | "internship" | "owner" | null;
    slug: string | null;
  }>;
  ownApps: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    deck: {
      en?: string;
      nl?: string;
    } | null;
    year: number | null;
    state: "cancelled" | "done" | "live" | "paused" | null;
    liveUrl: string | null;
  }>;
};

// Source: src/sanity/queries/availability.ts
// Variable: AVAILABILITY_QUERY
// Query: *[_id == "availability"][0]{    status,    label,    nextOpening  }
export type AVAILABILITY_QUERY_RESULT =
  | {
      status: null;
      label: null;
      nextOpening: null;
    }
  | {
      status: "available" | "booked" | "next-opening" | null;
      label: {
        en?: string;
        nl?: string;
      } | null;
      nextOpening: string | null;
    }
  | {
      status: null;
      label: string | null;
      nextOpening: null;
    }
  | null;

// Source: src/sanity/queries/profile.ts
// Variable: PROFILE_QUERY
// Query: *[_id == "profile"][0]{    name,    tagline,    location,    email  }
export type PROFILE_QUERY_RESULT =
  | {
      name: null;
      tagline: null;
      location: null;
      email: null;
    }
  | {
      name: string | null;
      tagline: null;
      location: null;
      email: null;
    }
  | {
      name: string | null;
      tagline: {
        en?: string;
        nl?: string;
      } | null;
      location: string | null;
      email: string | null;
    }
  | null;

// Source: src/sanity/queries/projects.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(featured desc, year desc, name asc) {    _id,    name,    "slug": slug.current,    year,    endYear,    state,    engagement,    featured,    role,    client,    deck,    description,    outcome,    liveUrl,    githubUrl,    writeupUrl,    "employer": employer->{      _id,      name    },    "stack": stack[]->{      _id,      name,      "slug": slug.current,      category    },    "screenshots": screenshots[]{      _key,      alt,      "asset": asset->    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  year: number | null;
  endYear: number | null;
  state: "cancelled" | "done" | "live" | "paused" | null;
  engagement: "freelance" | "full-time" | "internship" | "owner" | null;
  featured: boolean | null;
  role: string | null;
  client: string | null;
  deck: {
    en?: string;
    nl?: string;
  } | null;
  description: {
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | null;
  outcome: {
    en?: string;
    nl?: string;
  } | null;
  liveUrl: string | null;
  githubUrl: string | null;
  writeupUrl: string | null;
  employer: {
    _id: string;
    name: string | null;
  } | null;
  stack: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    category: "frontend" | "ios" | "other" | "rails" | "tooling" | null;
  }> | null;
  screenshots: Array<{
    _key: string;
    alt: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  {\n    "profile": *[_id == "profile"][0]{\n      name,\n      tagline,\n      bio,\n      location,\n      email,\n      socialLinks,\n      vatNumber,\n      copyrightYear,\n      "portrait": portrait{\n        alt,\n        "asset": asset->\n      },\n      "cv": cv{\n        "asset": asset->\n      }\n    },\n    "employers": *[_type == "employer"] | order(startYear desc, order desc) {\n      _id,\n      name,\n      role,\n      startYear,\n      endYear,\n      engagement,\n      "slug": "employer-" + lower(name)\n    },\n    "ownApps": *[_type == "project" && engagement == "owner"] | order(featured desc, year desc) {\n      _id,\n      name,\n      "slug": slug.current,\n      deck,\n      year,\n      state,\n      liveUrl\n    }\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_id == "availability"][0]{\n    status,\n    label,\n    nextOpening\n  }\n': AVAILABILITY_QUERY_RESULT;
    '\n  *[_id == "profile"][0]{\n    name,\n    tagline,\n    location,\n    email\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(featured desc, year desc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    year,\n    endYear,\n    state,\n    engagement,\n    featured,\n    role,\n    client,\n    deck,\n    description,\n    outcome,\n    liveUrl,\n    githubUrl,\n    writeupUrl,\n    "employer": employer->{\n      _id,\n      name\n    },\n    "stack": stack[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      category\n    },\n    "screenshots": screenshots[]{\n      _key,\n      alt,\n      "asset": asset->\n    }\n  }\n': PROJECTS_QUERY_RESULT;
  }
}
